# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-23 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20190323_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('vacant', 'VACANT'), ('occupied', 'OCCUPIED')], max_length=20),
        ),
    ]
